### ISSUE TITLE
Arithmetic errors when mixing floating points and integers (division) (v0.6.0)

### ISSUE THREAD

**Issue by spiff72** [c3d/DB48X-on-DM42#659] opened 2024-01-02 14:23 UTC
I haven't played around with my calc in a while, and I hadn't seen any release updates so I peeked this morning and saw that there were two!

Anyway - I saw in the changelog that unit prefix could be applied to Hz units so I gave it a try in v0.6.0 (I haven't tested in V0.5.2).

Steps to replicate:
enter 30e6 on the stack, and use the units menu to change it to 30e6 Hz
Use the double-shift CONV menu to apply the M (+6) prefix.

The resulting value on the stack is:
29.9998155011 MHz

Expected result would obviously be 30 MHz.

**Comment by spiff72** [comment] 2024-01-02 14:27
After another quick test, it seems there is something off in simple division operations:

Just entering 30e6 on the stack and dividing by 1000000 gives the same 29.9998155011 result?

**Comment by spiff72** [comment] 2024-01-02 16:54
One last comment - I tried a few different variants and I am finding that the issue seems to stem from integers vs floating point.

If I simply enter 30e6, and then 1000000 / (not using the E button), I get the incorrect value shown above.  the value for 1000000 appears to be an integer here (no decimal point shown).

If I enter 30e6 1e6 /   , then i get the right result.  The value for 1e6 shows a decimal point in this example.

**Comment by c3d** [comment] 2024-01-02 21:50
This appears to be a duplicate of #648, and works on my development branch.

The underlying issue is incorrect conversion from integer to decimal in some cases.

**Closed as completed** 2024-01-02 21:50 UTC
Labels: bug, duplicate, user, done
