### ISSUE TITLE
When a value having units is tagged, it doesn't convert to another units

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1252] opened 2024-10-13 17:51 UTC
For instance, if we have in the stack:
2     y:-1.52523_cm
1     1_in
CONVERT, leads to "Convert error: Bad argument type".
If I remove the tag with →NUM, it works fine as expected.

**Comment by c3d** [comment] 2024-10-14 00:51
This is a duplicate of #1246, already fixed. Closing.

**Closed as completed** 2024-10-14 00:53 UTC
Labels: bug, duplicate, done
