### ISSUE TITLE
LN on iOS brings up MathMenu

### ISSUE THREAD

**Issue by orome** [c3d/DB48X-on-DM42#1375] opened 2024-12-05 17:21 UTC
In the iOS app, pressing **`LN`** brings up `MathMenu`

**Comment by c3d** [comment] 2024-12-09 08:05
Duplicate of #1370 and #1364. Should be fixed in 0.8.8 on iOS.

**Closed as completed by c3d** 2024-12-09 08:05 UTC
Labels: bug, duplicate, user

**Comment by orome** [comment] 2024-12-09 13:00
This persists on 0.8.8.
