### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by Uli-Moin** [c3d/DB48X-on-DM42#1126] opened 2024-08-20 19:39 UTC
Hi,
I am using db48x on my iPhone 15 Pro and iPad Pro.
In both cases calculating is very slow.
I.e. 6 enter 8 enter + needs nearly one second.

**Comment by Uli-Moin** [comment] 2024-08-20 19:40
Correction: it needs 2 sec !

**Comment by mahi2003** [comment] 2024-08-21 04:18
Same issue as #1120.

**Comment by c3d** [comment] 2024-08-22 12:46
Thanks for reporting this. Can you confirm which version you observe this on? (use the `VERSION` command).

Also, as far as I can tell, it is not really a speed problem but a screen refresh problem. There is a condition which I did not fully identify yet which causes the screen to not be refreshed after a stack update.

**Comment by c3d** [comment] 2024-08-22 12:48
Also, at the moment, this does not reproduce on any of my devices, which makes it a bit more difficult to fix ;-)

**Comment by c3d** [comment] 2024-08-22 13:20
To confirm if the problem is a screen refresh issue as I think, can you please check that when you hit the problem, the keyboard remains responsive (and should also cause a screen refresh, e.g. if you type '1' you should see the editor pop up).

**Comment by Uli-Moin** [comment] 2024-08-22 13:22
HiIt is Version 0.7.14. Mit freundlichen GrüßenUli*Am 22.08.2024 um 14:47 schrieb Christophe de Dinechin ***@***.***>:﻿
Thanks for reporting this. Can you confirm which version you observe this on? (use the VERSION command).
Also, as far as I can tell, it is not really a speed problem but a screen refresh problem. There is a condition which I did not fully identify yet which causes the screen to not be refreshed after a stack update.

**Comment by Uli-Moin** [comment] 2024-08-22 13:25
Yes it is!!!If I press 3 Enter5 Enter+And when I press suddenly after „+“ the „1“ the result „8“ comes in this moment on the screen.  Mit freundlichen GrüßenUli*Am 22.08.2024 um 15:21 schrieb Christophe de Dinechin ***@***.***>:﻿
Too confirm if the problem is a screen refresh issue as I think, can you please check that when you hit the problem, the keyboard remains responsive (and should also cause a screen refresh, e.g. if you type '1' you should see the editor pop up).

**Comment by Uli-Moin** [comment] 2024-08-22 19:17
Yes!When I start the app the screen needs seconds to become white. But when I start the app it becomes white suddenly as soon as I press „1“. Hope it helps. Mit freundlichen GrüßenUli*Mit freundlichen GrüßenUli Am 22.08.2024 um 15:25 schrieb Uli  ***@***.***>:﻿Yes it is!!!If I press 3 Enter5 Enter+And when I press suddenly after „+“ the „1“ the result „8“ comes in this moment on the screen.  Mit freundlichen GrüßenUli*Am 22.08.2024 um 15:21 schrieb Christophe de Dinechin ***@***.***>:﻿
Too confirm if the problem is a screen refresh issue as I think, can you please check that when you hit the problem, the keyboard remains responsive (and should also cause a screen refresh, e.g. if you type '1' you should see the editor pop up).

**Comment by c3d** [comment] 2024-08-23 11:39
Installed the version from the app store, and the problem happens every single time. With my local builds of the app, they do not. That seems to narrow it down to some difference between debug and release build.

**Comment by c3d** [comment] 2024-08-23 11:45
Marking it as a duplicate of #1120

**Comment by c3d** [comment] 2024-08-23 22:01
OK, now my app store version does not show it anymore.

Also added schemes to my iOS builds to be able to build release and debug, and that's not it.

**Comment by c3d** [comment] 2024-09-08 05:33
This should be fixed now, closing that issue. @Uli-Moin, please test with 0.7.16, and reopen the issue if you still see the problem.

**Closed as completed** 2024-09-08 05:34 UTC
Labels: bug, duplicate, user, performance
