### ISSUE TITLE
Units conversions K <=> °C <=> °F are required in "Gases" of Equation Library

### ISSUE THREAD

**Issue by Wiljea** [c3d/DB48X-on-DM42#1287] opened 2024-10-26 15:53 UTC
I think there is an old unresolved issue related to that topic.

**Comment by c3d** [comment] 2024-11-02 09:57
> I think there is an old unresolved issue related to that topic.

Yes, it's #1064. I have a semi-working prototype with an approach that uses general expressions, and would therefore even enable non-linear conversions, e.g. Dalton temperature scale or dB to power.

Closing this one as a duplicate of #1064.

**Closed as completed** 2024-11-02 09:58 UTC
Labels: duplicate, feature, user
